name: Publish to Github packages

on:
  push:
    branches: [ configure-ci-cd ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        source-url: https://nuget.pkg.github.com/garethbaumgart/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Install dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    
    - name: Pack Nuget package	
      run: dotnet pack --no-build --configuration Release -o artifact

    - name: Publish Nuget package
      run: dotnet nuget push ./artifact/*.nupkg --skip-duplicate
    
